# Generated by Django 4.2.30 on 2026-07-03 17:54

import os

from django.contrib.auth.hashers import make_password
from django.db import migrations, models


def seed_settings(apps, schema_editor):
    RestaurantSettings = apps.get_model("core", "RestaurantSettings")
    RestaurantSettings.objects.get_or_create(
        pk=1,
        defaults={
            "logo_path": "assets/images/logo.jpg",
            "backoffice_password_hash": make_password(os.environ.get("ADMIN_PASSWORD", "change-this-admin-password")),
            "map_iframe_src": "https://www.google.com/maps?q=Chingiz%20Aytmatov%2044%2C%20Yunusabad%2C%20Tashkent&output=embed",
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('logo', models.FileField(blank=True, upload_to='settings/')),
                ('logo_path', models.CharField(default='assets/images/logo.jpg', help_text='Fallback static logo path. Used when no logo file is uploaded.', max_length=255)),
                ('backoffice_password_hash', models.CharField(blank=True, editable=False, max_length=255)),
                ('map_iframe_src', models.TextField(blank=True, default='https://www.google.com/maps?q=Chingiz%20Aytmatov%2044%2C%20Yunusabad%2C%20Tashkent&output=embed', help_text='Paste a Google Maps iframe src URL or the full iframe code.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Restaurant setting',
                'verbose_name_plural': 'Restaurant settings',
            },
        ),
        migrations.RunPython(seed_settings, migrations.RunPython.noop),
    ]
