# Generated by Django 4.2.30 on 2026-07-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_restaurantsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='meta_description',
            field=models.TextField(blank=True, default='', help_text='Default SEO meta description for the landing pages. Leave empty to use translated defaults.'),
        ),
    ]
